version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "10:00"
      timezone: "America/Denver"
    groups:
      pip-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "11:00"
      timezone: "America/Denver"
    groups:
      github-actions-dependencies:
        patterns: ["*"]
