"""
REST API Adapters - Digital Identity

FastAPI routers for the Digital Identity API.
Uses URL path versioning: /v1/identity/
"""

from digital_identity.infrastructure.adapters.rest.routers import (
    trust_profile_router,
    credential_template_router,
    presentation_policy_router,
    deployment_profile_router,
    flow_router,
    revocation_profile_router,
    application_template_router,
    verification_session_router,
    compliance_profile_router,
    lane_router,
    trust_framework_router,
    org_trust_profile_router,
    organization_router,
    webhook_router,
    subscription_router,
    api_key_router,
    issuance_record_router,
    policy_set_router,
    wallet_profile_router,
    device_registration_router,
    applicant_router,
    reviewer_lock_router,
    vetting_check_router,
    biometric_enrollment_router,
    notification_payload_router,
)
from digital_identity.infrastructure.adapters.rest.credential_router import (
    router as credential_router,
)
from digital_identity.infrastructure.adapters.rest.issuer_router import (
    issuer_router,
    cascade_router,
)
from digital_identity.infrastructure.adapters.rest.device_router import (
    device_router,
)
from digital_identity.infrastructure.adapters.rest.trust_anchors import (
    trust_anchor_router,
)
from digital_identity.infrastructure.adapters.rest.schemas import (
    TrustProfileCreate,
    TrustProfileUpdate,
    TrustProfileResponse,
    CredentialTemplateCreate,
    CredentialTemplateUpdate,
    CredentialTemplateResponse,
    PresentationPolicyCreate,
    PresentationPolicyUpdate,
    PresentationPolicyResponse,
    DeploymentProfileCreate,
    DeploymentProfileUpdate,
    DeploymentProfileResponse,
    FlowCreate,
    FlowUpdate,
    FlowResponse,
    FlowExecutionStart,
    FlowExecutionApproval,
    FlowExecutionResponse,
    RevocationProfileCreate,
    RevocationProfileUpdate,
    RevocationProfileResponse,
    ApplicationTemplateCreate,
    ApplicationTemplateUpdate,
    ApplicationTemplateResponse,
    VerificationSessionCreate,
    VerificationSessionUpdate,
    VerificationSessionResponse,
    ComplianceProfileCreate,
    ComplianceProfileUpdate,
    ComplianceProfileResponse,
    TrustFrameworkCreate,
    TrustFrameworkUpdate,
    TrustFrameworkResponse,
    OrganizationTrustProfileCreate,
    OrganizationTrustProfileUpdate,
    OrganizationTrustProfileResponse,
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationResponse,
    WebhookCreate,
    WebhookUpdate,
    WebhookResponse,
    SubscriptionCreate,
    SubscriptionUpdate,
    SubscriptionResponse,
    ApiKeyCreate,
    ApiKeyUpdate,
    ApiKeyResponse,
    IssuanceRecordCreate,
    IssuanceRecordUpdate,
    IssuanceRecordResponse,
    PolicySetCreate,
    PolicySetUpdate,
    PolicySetResponse,
    WalletProfileCreate,
    WalletProfileUpdate,
    WalletProfileResponse,
    DeviceRegistrationCreate,
    DeviceRegistrationUpdate,
    DeviceRegistrationResponse,
    ApplicantCreate,
    ApplicantUpdate,
    ApplicantResponse,
    ReviewerLockCreate,
    ReviewerLockResponse,
    VettingCheckCreate,
    VettingCheckUpdate,
    VettingCheckResponse,
    BiometricEnrollmentCreate,
    BiometricEnrollmentUpdate,
    BiometricEnrollmentResponse,
    NotificationPayloadCreate,
    NotificationPayloadResponse,
    NotificationTargetSchema,
)

__all__ = [
    # Routers
    "trust_profile_router",
    "credential_template_router",
    "presentation_policy_router",
    "deployment_profile_router",
    "flow_router",
    "revocation_profile_router",
    "application_template_router",
    "verification_session_router",
    "compliance_profile_router",
    "lane_router",
    "credential_router",
    "issuer_router",
    "cascade_router",
    "device_router",
    "trust_anchor_router",
    "trust_framework_router",
    "org_trust_profile_router",
    "organization_router",
    "webhook_router",
    "subscription_router",
    "api_key_router",
    "issuance_record_router",
    "policy_set_router",
    "wallet_profile_router",
    "device_registration_router",
    "applicant_router",
    "reviewer_lock_router",
    "vetting_check_router",
    "biometric_enrollment_router",
    "notification_payload_router",
    # Trust Profile Schemas
    "TrustProfileCreate",
    "TrustProfileUpdate",
    "TrustProfileResponse",
    # Credential Template Schemas
    "CredentialTemplateCreate",
    "CredentialTemplateUpdate",
    "CredentialTemplateResponse",
    # Presentation Policy Schemas
    "PresentationPolicyCreate",
    "PresentationPolicyUpdate",
    "PresentationPolicyResponse",
    # Deployment Profile Schemas
    "DeploymentProfileCreate",
    "DeploymentProfileUpdate",
    "DeploymentProfileResponse",
    # Flow Schemas
    "FlowCreate",
    "FlowUpdate",
    "FlowResponse",
    "FlowExecutionStart",
    "FlowExecutionApproval",
    "FlowExecutionResponse",
    # Revocation Profile Schemas
    "RevocationProfileCreate",
    "RevocationProfileUpdate",
    "RevocationProfileResponse",
    # Application Template Schemas
    "ApplicationTemplateCreate",
    "ApplicationTemplateUpdate",
    "ApplicationTemplateResponse",
    # Verification Session Schemas
    "VerificationSessionCreate",
    "VerificationSessionUpdate",
    "VerificationSessionResponse",
    # Compliance Profile Schemas
    "ComplianceProfileCreate",
    "ComplianceProfileUpdate",
    "ComplianceProfileResponse",
    # Trust Framework Schemas
    "TrustFrameworkCreate",
    "TrustFrameworkUpdate",
    "TrustFrameworkResponse",
    # Organization Trust Profile Schemas
    "OrganizationTrustProfileCreate",
    "OrganizationTrustProfileUpdate",
    "OrganizationTrustProfileResponse",
    # Organization Schemas
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    # Webhook Schemas
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookResponse",
    # Subscription Schemas
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "SubscriptionResponse",
    # API Key Schemas
    "ApiKeyCreate",
    "ApiKeyUpdate",
    "ApiKeyResponse",
    # Issuance Record Schemas
    "IssuanceRecordCreate",
    "IssuanceRecordUpdate",
    "IssuanceRecordResponse",
    # Policy Set Schemas
    "PolicySetCreate",
    "PolicySetUpdate",
    "PolicySetResponse",
    # Wallet Profile Schemas
    "WalletProfileCreate",
    "WalletProfileUpdate",
    "WalletProfileResponse",
    # Device Registration Schemas
    "DeviceRegistrationCreate",
    "DeviceRegistrationUpdate",
    "DeviceRegistrationResponse",
    # Applicant Schemas
    "ApplicantCreate",
    "ApplicantUpdate",
    "ApplicantResponse",
    # Reviewer Lock Schemas
    "ReviewerLockCreate",
    "ReviewerLockResponse",
    # Vetting Check Schemas
    "VettingCheckCreate",
    "VettingCheckUpdate",
    "VettingCheckResponse",
    # Biometric Enrollment Schemas
    "BiometricEnrollmentCreate",
    "BiometricEnrollmentUpdate",
    "BiometricEnrollmentResponse",
    # Notification Payload Schemas
    "NotificationPayloadCreate",
    "NotificationPayloadResponse",
    "NotificationTargetSchema",
]
