"""Utilities for provisioning and retrieving Document Signer certificates.

The Document Signer (DSC) certificate is required for:

* Embedding inside SOD structures generated by the passport personalization
  pipeline.
* Verifying signatures on SODs, DTC payloads, and other artifacts produced by
  the document_signer service.

This helper ensures that a consistent certificate exists for the configured
signing key. When none is present, it issues a self-signed certificate bound to
that key and persists it via the shared ``CertificateRepository``.
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Any

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa, padding
from cryptography.x509.oid import NameOID
from sqlalchemy.ext.asyncio import AsyncSession

from marty_plugin.common.infrastructure import CertificateRepository, KeyVaultClient

logger = logging.getLogger(__name__)

# Import Rust bindings for certificate building
from _marty_verification import (
    build_self_signed_certificate_with_key as rust_build_cert_with_key,
    certificate_der_to_pem as rust_cert_der_to_pem,
)

DOCUMENT_SIGNER_CERT_ID = "document-signer-default-dsc"
DOCUMENT_SIGNER_SUBJECT = "CN=Document Signer,O=Marty Labs"
DOCUMENT_SIGNER_KEY_ID = "document-signer-default"


def _parse_subject_dn(subject_dn: str) -> tuple[str | None, str | None, str | None]:
    """Parse RFC 4514 subject DN to extract CN, O, and C components."""
    cn = None
    org = None
    country = None
    for part in subject_dn.split(","):
        part = part.strip()
        if part.startswith("CN="):
            cn = part[3:]
        elif part.startswith("O="):
            org = part[2:]
        elif part.startswith("C="):
            country = part[2:]
    return cn, org, country


def _map_key_type(signing_algorithm: str) -> str:
    """Map signing algorithm name to Rust key type string."""
    algo_lower = signing_algorithm.lower()
    if algo_lower in ("rsa2048", "rsa-2048"):
        return "rsa2048"
    elif algo_lower in ("rsa3072", "rsa-3072"):
        return "rsa3072"
    elif algo_lower in ("rsa4096", "rsa-4096"):
        return "rsa4096"
    elif algo_lower in ("ecdsa-p256", "ec-p256", "p256"):
        return "ecdsa-p256"
    elif algo_lower in ("ecdsa-p384", "ec-p384", "p384"):
        return "ecdsa-p384"
    elif algo_lower in ("ed25519",):
        return "ed25519"
    # Default to RSA if unknown
    return "rsa2048"


async def ensure_document_signer_certificate(
    session: AsyncSession,
    key_vault: KeyVaultClient,
    certificate_id: str = DOCUMENT_SIGNER_CERT_ID,
    subject_dn: str = DOCUMENT_SIGNER_SUBJECT,
    key_id: str = DOCUMENT_SIGNER_KEY_ID,
    validity_years: int = 5,
    signing_algorithm: str = "rsa2048",
    kms_provider: Any | None = None,
) -> x509.Certificate:
    """Ensure that a DSC exists for the given signing key and return it.
    
    Args:
        session: Database session for certificate storage.
        key_vault: KeyVault client for key management.
        certificate_id: Unique ID for the certificate in the repository.
        subject_dn: RFC 4514 formatted subject distinguished name.
        key_id: ID of the signing key in the KeyVault.
        validity_years: Certificate validity period in years.
        signing_algorithm: Key algorithm (rsa2048, ecdsa-p256, etc.).
        kms_provider: Optional KMSProviderInterface for remote signing.
            When provided, the private key stays inside the KMS boundary
            and signing is performed via a CSR workflow.
    
    Returns:
        The DSC certificate.
    """
    repository = CertificateRepository(session)
    record = await repository.get(certificate_id)
    if record:
        return x509.load_pem_x509_certificate(record.pem.encode("utf-8"))

    now = datetime.now(timezone.utc)

    if kms_provider is not None:
        # KMS-backed CSR workflow: private key never leaves the KMS
        pem_text = await _build_dsc_via_kms(
            kms_provider=kms_provider,
            key_id=key_id,
            subject_dn=subject_dn,
            validity_years=validity_years,
            signing_algorithm=signing_algorithm,
        )
    else:
        # Legacy path: load private key from KeyVault
        await key_vault.ensure_key(key_id, signing_algorithm)
        private_key_pem = await key_vault.load_private_key(key_id)
        pem_text = _build_dsc_with_rust(
            private_key_pem=private_key_pem,
            subject_dn=subject_dn,
            validity_years=validity_years,
            signing_algorithm=signing_algorithm,
        )

    certificate = x509.load_pem_x509_certificate(pem_text.encode("utf-8"))

    details = {
        "issued_at": now.isoformat(),
        "not_after": (now + timedelta(days=365 * validity_years)).isoformat(),
        "key_id": key_id,
        "signing_algorithm": signing_algorithm,
        "implementation": "rust",
    }

    await repository.upsert(
        cert_id=certificate_id,
        cert_type="DSC",
        pem=pem_text,
        issuer=subject_dn,
        subject=subject_dn,
        details=details,
    )

    return certificate


def _build_dsc_with_rust(
    private_key_pem: bytes,
    subject_dn: str,
    validity_years: int,
    signing_algorithm: str,
) -> str:
    """Build a DSC using the Rust cert_builder."""
    cn, org, country = _parse_subject_dn(subject_dn)
    key_type = _map_key_type(signing_algorithm)
    
    # Decode bytes to string if needed
    if isinstance(private_key_pem, bytes):
        private_key_pem_str = private_key_pem.decode("utf-8")
    else:
        private_key_pem_str = private_key_pem
    
    # Build self-signed certificate with existing key
    cert_der = rust_build_cert_with_key(
        private_key_pem=private_key_pem_str,
        common_name=cn or "Document Signer",
        validity_days=365 * validity_years,
        key_type=key_type,
        is_ca=False,
        country=country,
        organization=org,
    )
    
    # Convert DER to PEM
    pem_text = rust_cert_der_to_pem(cert_der)
    return pem_text


async def _build_dsc_via_kms(
    kms_provider: Any,
    key_id: str,
    subject_dn: str,
    validity_years: int,
    signing_algorithm: str,
) -> str:
    """Build a DSC where the private key stays inside the KMS.

    1. Retrieves the public key from the KMS.
    2. Builds a TBSCertificate with that public key using a throw-away local
       key (the `cryptography` builder embeds the KMS public key set via
       `.public_key()`; the temp key is only used to produce well-formed DER).
    3. Signs the TBS bytes exclusively via the KMS (private key never leaves
       the KMS boundary).
    4. Reassembles the final certificate DER using minimal ASN.1 encoding and
       `asn1crypto` (already a transitive dependency of `cryptography`).
    """
    from marty_backend_common.crypto.role_separation import (
        CryptoRole,
        KeyIdentity,
        KeyPurpose,
    )

    key_identity = KeyIdentity(
        role=CryptoRole.DSC,
        purpose=KeyPurpose.DOCUMENT_SIGNING,
        key_id=key_id,
    )

    # Step 1: Retrieve the public key from the KMS.
    public_key_pem = await kms_provider.get_public_key(key_identity)
    public_key = serialization.load_pem_public_key(public_key_pem)

    cn, org, country = _parse_subject_dn(subject_dn)
    name_attrs = []
    if cn:
        name_attrs.append(x509.NameAttribute(NameOID.COMMON_NAME, cn))
    if org:
        name_attrs.append(x509.NameAttribute(NameOID.ORGANIZATION_NAME, org))
    if country:
        name_attrs.append(x509.NameAttribute(NameOID.COUNTRY_NAME, country))
    subject = x509.Name(name_attrs)

    now = datetime.now(timezone.utc)
    not_after = now + timedelta(days=365 * validity_years)

    builder = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(subject)
        .public_key(public_key)  # KMS public key embedded in TBS
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(not_after)
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                content_commitment=True,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=False,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
    )

    # Determine signing algorithm and generate a matching throw-away local key.
    algo_lower = signing_algorithm.lower()
    if "ed25519" in algo_lower:
        sig_algorithm = "EdDSA"
        _asn1_alg_name = "ed25519"
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey as _Ed
        _temp_key = _Ed.generate()
        _hash_alg = hashes.SHA256()  # unused for EdDSA but sign() requires it
    elif "p384" in algo_lower or "384" in algo_lower:
        sig_algorithm = "ES384"
        _asn1_alg_name = "sha384_ecdsa"
        _temp_key = ec.generate_private_key(ec.SECP384R1())
        _hash_alg = hashes.SHA384()
    elif "ec" in algo_lower or "p256" in algo_lower or "es256" in algo_lower:
        sig_algorithm = "ES256"
        _asn1_alg_name = "sha256_ecdsa"
        _temp_key = ec.generate_private_key(ec.SECP256R1())
        _hash_alg = hashes.SHA256()
    else:
        # RSA (default)
        sig_algorithm = "RS256"
        _asn1_alg_name = "sha256_rsa"
        _temp_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        _hash_alg = hashes.SHA256()

    # Step 2: Build a temp-signed cert to produce properly structured DER.
    # CertificateBuilder.public_key() controls SPKI in TBS; the temp key is
    # used ONLY for the throw-away signature to satisfy the builder API.
    _temp_cert = builder.sign(_temp_key, _hash_alg)
    _cert_der = _temp_cert.public_bytes(serialization.Encoding.DER)

    # Extract TBS bytes using asn1crypto (transitive dep of cryptography).
    try:
        from asn1crypto.x509 import Certificate as _Asn1Cert
        from asn1crypto import algos as _asn1_algos, pem as _asn1_pem
    except ImportError as exc:
        raise RuntimeError(
            "asn1crypto is required for KMS-backed DSC issuance; pip install asn1crypto"
        ) from exc

    _parsed = _Asn1Cert.load(_cert_der)
    tbs_der = _parsed["tbs_certificate"].dump()

    # Step 3: Sign the actual TBS bytes via the KMS.
    # The private key never leaves the KMS boundary.
    signature = await kms_provider.sign(
        key_identity=key_identity,
        data=tbs_der,
        algorithm=sig_algorithm,
    )

    # Step 4: Reassemble the final certificate DER.
    # Certificate ::= SEQUENCE { TBSCertificate, AlgorithmIdentifier, BIT STRING }
    sig_alg = _asn1_algos.SignedDigestAlgorithm({"algorithm": _asn1_alg_name})
    sig_alg_bytes = sig_alg.dump()

    # BIT STRING: tag=0x03, length, 0x00 (unused bits), signature bytes
    _sig_content = b"\x00" + signature
    _sig_len = len(_sig_content)
    if _sig_len < 0x80:
        sig_bs_bytes = bytes([0x03, _sig_len]) + _sig_content
    elif _sig_len < 0x100:
        sig_bs_bytes = bytes([0x03, 0x81, _sig_len]) + _sig_content
    else:
        sig_bs_bytes = bytes([0x03, 0x82, _sig_len >> 8, _sig_len & 0xFF]) + _sig_content

    _inner = tbs_der + sig_alg_bytes + sig_bs_bytes
    _inner_len = len(_inner)
    if _inner_len < 0x80:
        cert_der = bytes([0x30, _inner_len]) + _inner
    elif _inner_len < 0x100:
        cert_der = bytes([0x30, 0x81, _inner_len]) + _inner
    else:
        cert_der = bytes([0x30, 0x82, _inner_len >> 8, _inner_len & 0xFF]) + _inner

    cert_pem = _asn1_pem.armor("CERTIFICATE", cert_der).decode("ascii")
    logger.info("Built DSC via KMS (key_id=%s, algorithm=%s)", key_id, signing_algorithm)
    return cert_pem


async def get_document_signer_certificate(
    session: AsyncSession,
    certificate_id: str = DOCUMENT_SIGNER_CERT_ID,
) -> x509.Certificate | None:
    """Fetch an existing DSC from the repository if present."""
    repository = CertificateRepository(session)
    record = await repository.get(certificate_id)
    if record is None:
        return None
    return x509.load_pem_x509_certificate(record.pem.encode("utf-8"))


async def load_or_create_document_signer_certificate(
    session: AsyncSession,
    key_vault: KeyVaultClient,
    *,
    signing_algorithm: str = "rsa2048",
    key_id: str = DOCUMENT_SIGNER_KEY_ID,
    kms_provider: Any | None = None,
) -> x509.Certificate:
    """Convenience helper that loads the DSC or provisions a new one.
    
    Args:
        session: Database session for certificate storage.
        key_vault: KeyVault client for key management.
        signing_algorithm: Key algorithm (rsa2048, ecdsa-p256, etc.).
        key_id: ID of the signing key in the KeyVault.
        kms_provider: Optional KMS provider for remote signing.
    
    Returns:
        The DSC certificate.
    """
    certificate = await get_document_signer_certificate(session)
    if certificate:
        return certificate
    return await ensure_document_signer_certificate(
        session,
        key_vault,
        signing_algorithm=signing_algorithm,
        key_id=key_id,
        kms_provider=kms_provider,
    )


__all__ = [
    "DOCUMENT_SIGNER_CERT_ID",
    "DOCUMENT_SIGNER_KEY_ID",
    "DOCUMENT_SIGNER_SUBJECT",
    "ensure_document_signer_certificate",
    "get_document_signer_certificate",
    "load_or_create_document_signer_certificate",
]
