# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import open_badges_service_pb2 as open__badges__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in open_badges_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpenBadgesServiceStub(object):
    """Open Badges service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueOpenBadge = channel.unary_unary(
                '/marty.open_badges.v1.OpenBadgesService/IssueOpenBadge',
                request_serializer=open__badges__service__pb2.IssueOpenBadgeRequest.SerializeToString,
                response_deserializer=open__badges__service__pb2.IssueOpenBadgeResponse.FromString,
                _registered_method=True)
        self.VerifyOpenBadge = channel.unary_unary(
                '/marty.open_badges.v1.OpenBadgesService/VerifyOpenBadge',
                request_serializer=open__badges__service__pb2.VerifyOpenBadgeRequest.SerializeToString,
                response_deserializer=open__badges__service__pb2.VerifyOpenBadgeResponse.FromString,
                _registered_method=True)
        self.GetTrustStore = channel.unary_unary(
                '/marty.open_badges.v1.OpenBadgesService/GetTrustStore',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=open__badges__service__pb2.GetTrustStoreResponse.FromString,
                _registered_method=True)
        self.UpsertTrustStore = channel.unary_unary(
                '/marty.open_badges.v1.OpenBadgesService/UpsertTrustStore',
                request_serializer=open__badges__service__pb2.UpsertTrustStoreRequest.SerializeToString,
                response_deserializer=open__badges__service__pb2.UpsertTrustStoreResponse.FromString,
                _registered_method=True)


class OpenBadgesServiceServicer(object):
    """Open Badges service
    """

    def IssueOpenBadge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOpenBadge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrustStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertTrustStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenBadgesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueOpenBadge': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueOpenBadge,
                    request_deserializer=open__badges__service__pb2.IssueOpenBadgeRequest.FromString,
                    response_serializer=open__badges__service__pb2.IssueOpenBadgeResponse.SerializeToString,
            ),
            'VerifyOpenBadge': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOpenBadge,
                    request_deserializer=open__badges__service__pb2.VerifyOpenBadgeRequest.FromString,
                    response_serializer=open__badges__service__pb2.VerifyOpenBadgeResponse.SerializeToString,
            ),
            'GetTrustStore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrustStore,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=open__badges__service__pb2.GetTrustStoreResponse.SerializeToString,
            ),
            'UpsertTrustStore': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertTrustStore,
                    request_deserializer=open__badges__service__pb2.UpsertTrustStoreRequest.FromString,
                    response_serializer=open__badges__service__pb2.UpsertTrustStoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marty.open_badges.v1.OpenBadgesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marty.open_badges.v1.OpenBadgesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpenBadgesService(object):
    """Open Badges service
    """

    @staticmethod
    def IssueOpenBadge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.open_badges.v1.OpenBadgesService/IssueOpenBadge',
            open__badges__service__pb2.IssueOpenBadgeRequest.SerializeToString,
            open__badges__service__pb2.IssueOpenBadgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOpenBadge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.open_badges.v1.OpenBadgesService/VerifyOpenBadge',
            open__badges__service__pb2.VerifyOpenBadgeRequest.SerializeToString,
            open__badges__service__pb2.VerifyOpenBadgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrustStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.open_badges.v1.OpenBadgesService/GetTrustStore',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            open__badges__service__pb2.GetTrustStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertTrustStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marty.open_badges.v1.OpenBadgesService/UpsertTrustStore',
            open__badges__service__pb2.UpsertTrustStoreRequest.SerializeToString,
            open__badges__service__pb2.UpsertTrustStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
