"""Utilities for provisioning and retrieving Document Signer certificates.

The Document Signer (DSC) certificate is required for:

* Embedding inside SOD structures generated by the passport personalization
  pipeline.
* Verifying signatures on SODs, DTC payloads, and other artifacts produced by
  the document_signer service.

This helper ensures that a consistent certificate exists for the configured
signing key. When none is present, it issues a self-signed certificate bound to
that key and persists it via the shared ``CertificateRepository``.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

from cryptography import x509
from sqlalchemy.ext.asyncio import AsyncSession

from marty_plugin.common.infrastructure import CertificateRepository, KeyVaultClient

# Import Rust bindings for certificate building
from _marty_verification import (
    build_self_signed_certificate_with_key as rust_build_cert_with_key,
    certificate_der_to_pem as rust_cert_der_to_pem,
)

DOCUMENT_SIGNER_CERT_ID = "document-signer-default-dsc"
DOCUMENT_SIGNER_SUBJECT = "CN=Document Signer,O=Marty Labs"
DOCUMENT_SIGNER_KEY_ID = "document-signer-default"


def _parse_subject_dn(subject_dn: str) -> tuple[str | None, str | None, str | None]:
    """Parse RFC 4514 subject DN to extract CN, O, and C components."""
    cn = None
    org = None
    country = None
    for part in subject_dn.split(","):
        part = part.strip()
        if part.startswith("CN="):
            cn = part[3:]
        elif part.startswith("O="):
            org = part[2:]
        elif part.startswith("C="):
            country = part[2:]
    return cn, org, country


def _map_key_type(signing_algorithm: str) -> str:
    """Map signing algorithm name to Rust key type string."""
    algo_lower = signing_algorithm.lower()
    if algo_lower in ("rsa2048", "rsa-2048"):
        return "rsa2048"
    elif algo_lower in ("rsa3072", "rsa-3072"):
        return "rsa3072"
    elif algo_lower in ("rsa4096", "rsa-4096"):
        return "rsa4096"
    elif algo_lower in ("ecdsa-p256", "ec-p256", "p256"):
        return "ecdsa-p256"
    elif algo_lower in ("ecdsa-p384", "ec-p384", "p384"):
        return "ecdsa-p384"
    elif algo_lower in ("ed25519",):
        return "ed25519"
    # Default to RSA if unknown
    return "rsa2048"


async def ensure_document_signer_certificate(
    session: AsyncSession,
    key_vault: KeyVaultClient,
    certificate_id: str = DOCUMENT_SIGNER_CERT_ID,
    subject_dn: str = DOCUMENT_SIGNER_SUBJECT,
    key_id: str = DOCUMENT_SIGNER_KEY_ID,
    validity_years: int = 5,
    signing_algorithm: str = "rsa2048",
) -> x509.Certificate:
    """Ensure that a DSC exists for the given signing key and return it.
    
    Args:
        session: Database session for certificate storage.
        key_vault: KeyVault client for key management.
        certificate_id: Unique ID for the certificate in the repository.
        subject_dn: RFC 4514 formatted subject distinguished name.
        key_id: ID of the signing key in the KeyVault.
        validity_years: Certificate validity period in years.
        signing_algorithm: Key algorithm (rsa2048, ecdsa-p256, etc.).
    
    Returns:
        The DSC certificate.
    """
    repository = CertificateRepository(session)
    record = await repository.get(certificate_id)
    if record:
        return x509.load_pem_x509_certificate(record.pem.encode("utf-8"))

    # Make sure key material exists
    await key_vault.ensure_key(key_id, signing_algorithm)
    private_key_pem = await key_vault.load_private_key(key_id)
    
    now = datetime.now(timezone.utc)
    
    # Use Rust implementation for certificate building
    pem_text = _build_dsc_with_rust(
        private_key_pem=private_key_pem,
        subject_dn=subject_dn,
        validity_years=validity_years,
        signing_algorithm=signing_algorithm,
    )
    certificate = x509.load_pem_x509_certificate(pem_text.encode("utf-8"))

    details = {
        "issued_at": now.isoformat(),
        "not_after": (now + timedelta(days=365 * validity_years)).isoformat(),
        "key_id": key_id,
        "signing_algorithm": signing_algorithm,
        "implementation": "rust",
    }

    await repository.upsert(
        cert_id=certificate_id,
        cert_type="DSC",
        pem=pem_text,
        issuer=subject_dn,
        subject=subject_dn,
        details=details,
    )

    return certificate


def _build_dsc_with_rust(
    private_key_pem: bytes,
    subject_dn: str,
    validity_years: int,
    signing_algorithm: str,
) -> str:
    """Build a DSC using the Rust cert_builder."""
    cn, org, country = _parse_subject_dn(subject_dn)
    key_type = _map_key_type(signing_algorithm)
    
    # Decode bytes to string if needed
    if isinstance(private_key_pem, bytes):
        private_key_pem_str = private_key_pem.decode("utf-8")
    else:
        private_key_pem_str = private_key_pem
    
    # Build self-signed certificate with existing key
    cert_der = rust_build_cert_with_key(
        private_key_pem=private_key_pem_str,
        common_name=cn or "Document Signer",
        validity_days=365 * validity_years,
        key_type=key_type,
        is_ca=False,
        country=country,
        organization=org,
    )
    
    # Convert DER to PEM
    pem_text = rust_cert_der_to_pem(cert_der)
    return pem_text


async def get_document_signer_certificate(
    session: AsyncSession,
    certificate_id: str = DOCUMENT_SIGNER_CERT_ID,
) -> x509.Certificate | None:
    """Fetch an existing DSC from the repository if present."""
    repository = CertificateRepository(session)
    record = await repository.get(certificate_id)
    if record is None:
        return None
    return x509.load_pem_x509_certificate(record.pem.encode("utf-8"))


async def load_or_create_document_signer_certificate(
    session: AsyncSession,
    key_vault: KeyVaultClient,
    *,
    signing_algorithm: str = "rsa2048",
    key_id: str = DOCUMENT_SIGNER_KEY_ID,
) -> x509.Certificate:
    """Convenience helper that loads the DSC or provisions a new one.
    
    Args:
        session: Database session for certificate storage.
        key_vault: KeyVault client for key management.
        signing_algorithm: Key algorithm (rsa2048, ecdsa-p256, etc.).
        key_id: ID of the signing key in the KeyVault.
    
    Returns:
        The DSC certificate.
    """
    certificate = await get_document_signer_certificate(session)
    if certificate:
        return certificate
    return await ensure_document_signer_certificate(
        session,
        key_vault,
        signing_algorithm=signing_algorithm,
        key_id=key_id,
    )


__all__ = [
    "DOCUMENT_SIGNER_CERT_ID",
    "DOCUMENT_SIGNER_KEY_ID",
    "DOCUMENT_SIGNER_SUBJECT",
    "ensure_document_signer_certificate",
    "get_document_signer_certificate",
    "load_or_create_document_signer_certificate",
]
